### ISSUE TITLE
inputs

### ISSUE THREAD

**Issue by rufakm** [kit-cn-cms/karim#15]
While trying to create friend trees using ttbb_lepWeights, there is an error like
```
File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/configs/calculate_ttbb_lepWeightsUL.py", line 191, in calculate_variables
    idsf     = data[dataEra]["muID"].evaluate(  
RuntimeError: Insufficient inputs
```
I have received a response from Jan regarding this before as the muon and electron corrections were updated in december, the inputs have to be updated too. But I am not clearly understanding what are the inputs here.
Using
```
python3 -m correctionlib.cli summary /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/MUO/2018_UL/muon_Z.json.gz
```
as said, the inputs can be seen. But there are all the muTrigNames or others already as mentioned in the python file itself.
I don't clearly understand what these inputs are clearly and which to update??

**Comment by JanvanderLinden** [comment]
For the muons, previously these corrections were used:
```
    data[year]["muTrig"] = mu_evaluator[muTrigName[year]]
    data[year]["muID"]   = mu_evaluator["NUM_TightID_DEN_TrackerMuons"]
    data[year]["muISO"]  = mu_evaluator["NUM_TightRelIso_DEN_TightIDandIPCut"]
```
See [here](https://github.com/kit-cn-cms/karim/blob/dev_nanoAOD/configs/calculate_ttbb_lepWeightsUL.py#L42-L44) with [these](https://github.com/kit-cn-cms/karim/blob/dev_nanoAOD/configs/calculate_ttbb_lepWeightsUL.py#L12-L17) trigger names.

As there were many corrections with these names in the muon files (see [this issue](https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues/10)) these corrections have been updated to always be pt and eta dependent.

So if you search for the corrections (which are still named the same in the summary) you can find their binning, e.g.:
```bash
├── 📈 NUM_TightID_DEN_TrackerMuons (v1)                                                            
│   NUM_TightID_DEN_TrackerMuons                                                                    
│   Node counts: Category: 33, Binning: 5                                                           
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ year (string)                                                                                │
│   │ year/scenario: example 2016preVFP, 2017 etc                                                  │
│   │ Values: 2018_UL                                                                              │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ abseta (real)                                                                                │
│   │ Probe abseta                                                                                 │
│   │ Range: [0.0, 2.4)                                                                            │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ pt (real)                                                                                    │
│   │ Probe pt                                                                                     │
│   │ Range: [15.0, inf)                                                                           │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ ValType (string)                                                                             │
│   │ sf or syst (currently 'sf' is nominal, and 'systup' and 'systdown' are up/down variations    │
│   │ with total stat+syst uncertainties. Individual systs are also available (in these cases syst │
│   │ only, not sf +/- syst)                                                                       │
│   │ Values: AltSig, massBin, massRange, sf, stat, syst, systdown, systup, tagIso                 │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────── ◀ output ──────────────────╮                                                
│   │ weight (real)                                │                                                
│   │ Output scale factor (nominal) or uncertainty │                                                
│   ╰──────────────────────────────────────────────╯ 

```
So what you have to do is basically update these lines for the muons to the new inputs:
https://github.com/kit-cn-cms/karim/blob/dev_nanoAOD/configs/calculate_ttbb_lepWeightsUL.py#L181-L198

And here for the electrons:
https://github.com/kit-cn-cms/karim/blob/dev_nanoAOD/configs/calculate_ttbb_lepWeightsUL.py#L112-L135

Be aware, that we dont need the `min` function for these anymore, as the issue of forbidden overflows should be fixed [here](https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues/6), and a differentiation between the years isnt needed anymore either because of the previously mentioned fix [here](https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues/10).

**Comment by MartMarz** [comment]
So I ran into the same exact issue. I'm not quiet sure if I implemented the right fix, because I don't know the old formating. So I wanted to check with you if I had the rigth idea. The year should already be given by the dataEra and doesn't need to be a further input rigth?
```
idsf     = data[dataEra]["muID"].evaluate(
                    "2018_UL", abs(event.Mu_Eta[iMu]), event.Mu_Pt[iMu], "sf")
```
corrected command

**Comment by JanvanderLinden** [comment]
In principle you are correct and the dataEra is already given, but you have to see if the correction set you are using requires the dataEra as input, even though there are no choices.

Based on my comment above it does require the dataEra as input. For this one example the only valid choice seems to be `2018_UL`, as can be seen from these lines:
```
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ year (string)                                                                                │
│   │ year/scenario: example 2016preVFP, 2017 etc                                                  │
│   │ Values: 2018_UL                                                                              │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by MartMarz** [comment]
I ran into another Problem.
`Index below bounds in Binning for input argument 2 value: 25.053398`
What is the propper way to deal with this? The problem occurs because in my analysis Im working with the Medium working point of the Trigger rather then `NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight`. Nikita mentioned that there are no SF for the medium WP, at least not yet.

Should I exclude this trigger or `hack`it with a max function?

**Comment by rufakm** [comment]
> In principle you are correct and the dataEra is already given, but you have to see if the correction set you are using requires the dataEra as input, even though there are no choices.
> 
> Based on my comment above it does require the dataEra as input. For this one example the only valid choice seems to be `2018_UL`, as can be seen from these lines:
> 
> ```
> │   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
> │   │ year (string)                                                                                │
> │   │ year/scenario: example 2016preVFP, 2017 etc                                                  │
> │   │ Values: 2018_UL                                                                              │
> │   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
> ```

But if looked for the 2017_UL, we can see the same choice like
```
📈 NUM_TightID_DEN_TrackerMuons (v1)                                                            
│   NUM_TightID_DEN_TrackerMuons                                                                    
│   Node counts: Category: 33, Binning: 5                                                           
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ year (string)                                                                                │
│   │ year/scenario: example 2016preVFP, 2017 etc                                                  │
│   │ Values: 2017_UL                                                                              │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ abseta (real)                                                                                │
│   │ Probe abseta                                                                                 │
│   │ Range: [0.0, 2.4)                                                                            │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ pt (real)                                                                                    │
│   │ Probe pt                                                                                     │
│   │ Range: [15.0, inf)                                                                           │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────────────────────────────── ▶ input ───────────────────────────────────────────╮
│   │ ValType (string)                                                                             │
│   │ sf or syst (currently 'sf' is nominal, and 'systup' and 'systdown' are up/down variations    │
│   │ with total stat+syst uncertainties. Individual systs are also available (in these cases syst │
│   │ only, not sf +/- syst)                                                                       │
│   │ Values: AltSig, massBin, massRange, sf, stat, syst, systdown, systup, tagIso                 │
│   ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
│   ╭────────────────── ◀ output ──────────────────╮                                                
│   │ weight (real)                                │                                                
│   │ Output scale factor (nominal) or uncertainty │                                                
│   ╰──────────────────────────────────────────────╯   
```

**Comment by rufakm** [comment]
Even after giving the fix for each year 
```
for iMu in range(getattr(event, "nMu_tight")):
        if dataEra == "2018":
            idsf     = data[dataEra]["muID"].evaluate(
                        "2018_UL", abs(event.Mu_Eta[iMu]), event.Mu_Pt[iMu], "sf")
            idsfErr  = data[dataEra]["muID"].evaluate(
			"2018_UL", abs(event.Mu_Eta[iMu]), event.Mu_Pt[iMu], "syst")
            isosf    = data[dataEra]["muISO"].evaluate(
                        "2018_UL", abs(event.Mu_Eta[iMu]), event.Mu_Pt[iMu], "sf")
            isosfErr = data[dataEra]["muISO"].evaluate(
                        "2018_UL", abs(event.Mu_Eta[iMu]), event.Mu_Pt[iMu], "syst")
        elif dataEra == "2017":
            idsf     = data[dataEra]["muID"].evaluate(
                          "2017_UL", event.Mu_Pt_tight[iMu], "nominal")
            idsfErr  = data[dataEra]["muID"].evaluate(
                          "2017_UL", event.Mu_Pt_tight[iMu], "syst")
            isosf    = data[dataEra]["muISO"].evaluate(
                          "2017_UL", event.Mu_Pt_tight[iMu], "nominal")
            isosfErr = data[dataEra]["muISO"].evaluate(
                          "2017_UL", event.Mu_Pt_tight[iMu], "syst")
        elif dataEra == "2016preVPF":
            idsf     = data[dataEra]["muID"].evaluate(
                          "2016preVPF_UL", event.Mu_Pt_tight[iMu], "nominal")
            idsfErr  = data[dataEra]["muID"].evaluate(
                          "2016preVPF_UL", event.Mu_Pt_tight[iMu], "syst")
            isosf    = data[dataEra]["muISO"].evaluate(
                          "2016preVPF_UL", event.Mu_Pt_tight[iMu], "nominal")
            isosfErr = data[dataEra]["muISO"].evaluate(
                          "2016postVPF_UL", event.Mu_Pt_tight[iMu], "syst")



        muIDSF        *= idsf
        muIsoSF       *= isosf

        muIDSF_up     *= (idsf + idsfErr)
        muIDSF_down   *= (idsf - idsfErr)

        muIsoSF_up    *= (isosf + isosfErr)
        muIsoSF_down  *= (isosf - isosfErr)

        if dataEra == "2018":
            trig    = data[dataEra]["muTrig"].evaluate(
                       "2018_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "sf")
            trigErr = data[dataEra]["muTrig"].evaluate(
                       "2018_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "syst")
        if dataEra == "2017":
            trig    = data[dataEra]["muTrig"].evaluate(
                     "2017_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "sf")
            trigErr = data[dataEra]["muTrig"].evaluate(
                       "2017_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "syst")
        if dataEra == "2016preVPF":
            trig    = data[dataEra]["muTrig"].evaluate(
                       "2016preVPF_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "sf")
            trigErr = data[dataEra]["muTrig"].evaluate(
                       "2016preVPF_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "syst")
        if dataEra == "2016postVPF":
            trig    = data[dataEra]["muTrig"].evaluate(
                       "2016postVPF_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "sf")
            trigErr = data[dataEra]["muTrig"].evaluate(
                       "2016postVPF_UL", abs(event.Mu_Eta_tight[iMu]), event.Mu_Pt_tight[iMu], "syst")
```
it shows the same error of ```Insufficient Inputs```

**Comment by JanvanderLinden** [comment]
> I ran into another Problem. `Index below bounds in Binning for input argument 2 value: 25.053398` What is the propper way to deal with this? The problem occurs because in my analysis Im working with the Medium working point of the Trigger rather then `NUM_IsoMu24_DEN_CutBasedIdTight_and_PFIsoTight`. Nikita mentioned that there are no SF for the medium WP, at least not yet.
> 
> Should I exclude this trigger or `hack`it with a max function?

Generally you can try doing it with the `max` function, but I would be careful with low-pT jets and these SFs, there might be strong pT dependencies which then are not covered by your implementation.     
So it definitely wouldnt be a final implementation if you cut your pT at 30, but for the time being I think its fine

**Comment by JanvanderLinden** [comment]
@rufakm for 2017 you only supplied this with the eta values, the pT values are missing, so maybe this is the issue.

Also you can just use the `dataEra` variable for supplying the first argument instead of copying it for each data era, e.g.
```
idsf = data[dataEra]["muID"].evaluate(
   dataEra+"_UL", abs(event.Mu_Eta[iMu]), event.Mu_Pt[iMu], "sf")
```

Also you could adapt it such that directly the `systup` and `systdown` values are read instead of the `syst`. This is what is mentioned in this issue: 
https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/issues/11
and this HN thread:
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3794/1.html

**Comment by rufakm** [comment]
> 
Is this fix correct?
```
        idsfErr_up= data[dataEra]["electron"].evaluate(dataEra+"_UL","systup","Tight",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])
        idsfErr_down= data[dataEra]["electron"].evaluate(dataEra+"_UL","systdown","Tight",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])
        recosf    = data[dataEra]["electron"].evaluate(dataEra+"_UL","sf","RecoAbove20",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])
        recosfErr_up = data[dataEra]["electron"].evaluate(dataEra+"_UL","systup","RecoAbove20",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])

        recosfErr_down = data[dataEra]["electron"].evaluate(dataEra+"_UL","systdown","RecoAbove20",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])

        elIDSF        *= idsf
        elRecoSF      *= recosf

        elIDSF_up     *= (idsf + idsfErr_up + idsfErr_down)
        elIDSF_down   *= (idsf - idsfErr_up - idsfErr_down)

        elRecoSF_up   *= (recosf + recosfErr_up + recosfErr_down)
        elRecoSF_down *= (recosf - recosfErr_up - recosfErr_down)
```
Is the ```elIDSF_up``` is directly the ```idsfErr_up``` or is it as defined above?

**Comment by rufakm** [comment]
Also, there is some error with the 2017_UL dataEra,
```
Traceback (most recent call last):
  File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/scripts/karim.py", line 151, in <module>
    karim.calculate_variables(
  File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/karim/calculate.py", line 36, in calculate_variables
    config.calculate_variables(event, outfile, outfile.sampleName, None, dataEra, genWeights)
  File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/configs/calculate_ttbb_lepWeightsUL.py", line 119, in calculate_variables
    idsf      = data[dataEra]["electron"].evaluate(dataEra+"_UL","sf","Tight", 
IndexError: Index not available in Category for input argument 0 val: 2017_UL
```
The code lines corresponding to this error are:
```
for iEl in range(event.nEle_tight):
        idsf      = data[dataEra]["electron"].evaluate(dataEra+"_UL","sf","Tight",
                    event.Ele_Eta_tight[iEl], event.Ele_Pt_tight[iEl])                                                                                                                           
        idsfErr   = data[dataEra]["electron"].evaluate(dataEra+"_UL","syst","Tight",
                    event.Ele_Eta_tight[iEl], event.Ele_Pt_tight[iEl])
        recosf    = data[dataEra]["electron"].evaluate(dataEra+"_UL","sf","RecoAbove20",
                    event.Ele_Eta_tight[iEl], event.Ele_Pt_tight[iEl])
        recosfErr = data[dataEra]["electron"].evaluate(dataEra+"_UL","syst","RecoAbove20",
                    event.Ele_Eta_tight[iEl], event.Ele_Pt_tight[iEl])

        elIDSF        *= idsf
        elRecoSF      *= recosf

        elIDSF_up     *= (idsf + idsfErr)
        elIDSF_down   *= (idsf - idsfErr)

        elRecoSF_up   *= (recosf + recosfErr)
        elRecoSF_down *= (recosf - recosfErr)

        elTrigSF      *= data[dataEra]["eleTrig"].evaluate(dataEra+"_UL","central",
                         event.Ele_Pt_tight[iEl], event.Ele_Eta_tight[iEl])
        elTrigSF_up   *= data[dataEra]["eleTrig"].evaluate(dataEra+"_UL","up",
                         event.Ele_Pt_tight[iEl], event.Ele_Eta_tight[iEl])
        elTrigSF_down *= data[dataEra]["eleTrig"].evaluate(dataEra+"_UL","down",
                         event.Ele_Pt_tight[iEl], event.Ele_Eta_tight[iEl])
```

**Comment by rufakm** [comment]
The Index error problem was solved but I have another error which I am not able to track why.
```
Traceback (most recent call last):
  File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/scripts/karim.py", line 151, in <module>
    karim.calculate_variables(
  File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/karim/calculate.py", line 36, in calculate_variables
    config.calculate_variables(event, outfile, outfile.sampleName, None, dataEra, genWeights)
  File "/nfs/dust/cms/user/rrafeek/CMSSW_11_3_1/src/PhysicsTools/karim/configs/calculate_ttbb_lepWeightsUL.py", line 168, in calculate_variables
    wrapper.branchArrays["elTrigSF_up_rel"][0]   = elTrigSF_up/elTrigSF
ZeroDivisionError: float division by zero
```
I have used the Ele_Eta instead of Ele_EtaSC as it is not a branch in my ntuple set created. The Ele_EtaSC seems to be in range of -inf to inf.  Could someone please tell me what is the issue here?

**Comment by JanvanderLinden** [comment]
So summarizing from the discussions in Mattermost:
- the remaining open problem appears to be the difference between `EtaSC` and `Eta` of the electrons
- for the future these branches should be added to your ntuples
- for now you can assign a SF of 1 to the electrons in the `abs(1.4442-1.566)`

**Comment by JanvanderLinden** [comment]
> ```
>         elIDSF_up     *= (idsf + idsfErr_up + idsfErr_down)
>         elIDSF_down   *= (idsf - idsfErr_up - idsfErr_down)
> 
>         elRecoSF_up   *= (recosf + recosfErr_up + recosfErr_down)
>         elRecoSF_down *= (recosf - recosfErr_up - recosfErr_down)
> ```
> 
> Is the `elIDSF_up` is directly the `idsfErr_up` or is it as defined above?

The up and down variations as shown here are not correct. The purpose of reading directly things like `systup` and `systdown`, etc from the correction lib files is to circumvent having to add the SFs to the nominal by hand. So the values you get are already the varied SFs, so something like
```
        idsfErr_up= data[dataEra]["electron"].evaluate(dataEra+"_UL","systup","Tight",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])
        idsfErr_down= data[dataEra]["electron"].evaluate(dataEra+"_UL","systdown","Tight",
                    event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])

        elIDSF_up     *= idsfErr_up
        elIDSF_down   *= idsfErr_down
```
should be applied everywhere

**Comment by JanvanderLinden** [comment]
> Also, there is some error with the 2017_UL dataEra,
> ```
> for iEl in range(event.nEle_tight):
>         idsf      = data[dataEra]["electron"].evaluate(dataEra+"_UL","sf","Tight",
>                     event.Ele_Eta_tight[iEl], event.Ele_Pt_tight[iEl])   
> ```
I dont think the electron trigger SF files provided by @emanuelpf follow the same input structure as the other lepton SF files. You have to look at the json file summary of these to figure out which inputs are needed there

**Comment by rufakm** [comment]
> > ```
> >         elIDSF_up     *= (idsf + idsfErr_up + idsfErr_down)
> >         elIDSF_down   *= (idsf - idsfErr_up - idsfErr_down)
> > 
> >         elRecoSF_up   *= (recosf + recosfErr_up + recosfErr_down)
> >         elRecoSF_down *= (recosf - recosfErr_up - recosfErr_down)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is the `elIDSF_up` is directly the `idsfErr_up` or is it as defined above?
> 
> The up and down variations as shown here are not correct. The purpose of reading directly things like `systup` and `systdown`, etc from the correction lib files is to circumvent having to add the SFs to the nominal by hand. So the values you get are already the varied SFs, so something like
> 
> ```
>         idsfErr_up= data[dataEra]["electron"].evaluate(dataEra+"_UL","systup","Tight",
>                     event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])
>         idsfErr_down= data[dataEra]["electron"].evaluate(dataEra+"_UL","systdown","Tight",
>                     event.Ele_EtaSC[iEl], event.Ele_Pt_tight[iEl])
> 
>         elIDSF_up     *= idsfErr_up
>         elIDSF_down   *= idsfErr_down
> ```
> 
> should be applied everywhere

Ya, I applied those changes. Also in case of electrons, changed to sfup and sfdown instead of syst. I think it is right?

**Comment by rufakm** [comment]
> > Also, there is some error with the 2017_UL dataEra,
> > ```
> > for iEl in range(event.nEle_tight):
> >         idsf      = data[dataEra]["electron"].evaluate(dataEra+"_UL","sf","Tight",
> >                     event.Ele_Eta_tight[iEl], event.Ele_Pt_tight[iEl])   
> > ```
> 
> I dont think the electron trigger SF files provided by @emanuelpf follow the same input structure as the other lepton SF files. You have to look at the json file summary of these to figure out which inputs are needed there

Yes, the input structure in case of electron SF file was a bit different. The ```dataEra+"_UL"``` is not a valid input here but just ```dataEra``` is fine. I figured it later.

**Comment by emanuelpf** [comment]
You can get the summary of the correctiolib file with 
`python3 -m correctionlib.cli summary path/to/EleTriggerSF_NanoAODv2_v0.json`
to see what inputs are needed (in this case the variation (central/up/down), pT, and eta) to get the SF you want. A data era is not necessary in this case since I provide one file for each data era.

**Comment by JanvanderLinden** [comment]
I guess this has been resolved with https://github.com/kit-cn-cms/karim/pull/18

So I will go ahead and close this issue
