### ISSUE TITLE
bTag weights with huge difference

### ISSUE THREAD

**Issue by MartMarz** [kit-cn-cms/karim#16]
As mentioned in the group meeting I have a problem with the bTag Weights for my analysis.
The weights produced by Karim seem to be as expected. These can be found here `/nfs/dust/cms/user/mmarz/bsm_QCD/UL/friends/2018/friend_bTagWeightstest`. Nontheless they have a huge impact on the plots generated with https://gitlab.cern.ch/kit-cn-cms/hogwarts/-/blob/bsm_di_higgs/configs/bsm_di_higgs/bsm_di_higgs_SampleConfig.py#L40.

The Weights are generated with https://github.com/kit-cn-cms/karim/blob/bsm_di_higgs/configs/calculate_bsm_itFit_test.py

If I comment the bTag weights out the difference is enormous. This is the plot with the Weights:

With the Weights
![normalcuts_bJet_bTagDisSorted_M_withWeights](https://user-images.githubusercontent.com/90858509/151369063-30403f4f-0921-47e8-a6a0-c03f27c4d2f0.png)

Without the Weights
![normalcuts_bJet_bTagDisSorted_M_withoutWeights](https://user-images.githubusercontent.com/90858509/151369044-570335be-dbbd-41b6-8af9-4ae4c12149b6.png)

The weights for the three major backgrounds
[ohadd.pdf](https://github.com/kit-cn-cms/karim/files/7950758/ohadd.pdf)
[tttolep.pdf](https://github.com/kit-cn-cms/karim/files/7950759/tttolep.pdf)
[tttosemi.pdf](https://github.com/kit-cn-cms/karim/files/7950760/tttosemi.pdf)

What could be the reason for that behaviour?

**Comment by sebwieland** [comment]
Just two quick thoughts (I am not an expert at this but it spotted my eye):
1.) you're only looping over tagged jets (https://github.com/kit-cn-cms/karim/blob/bsm_di_higgs/configs/calculate_bsm_itFit_test.py#L75). to my understanding one should consider every jet in an event.
2.) I am not really sure about this if condition: https://github.com/kit-cn-cms/karim/blob/bsm_di_higgs/configs/calculate_bsm_itFit_test.py#L77
Here again you are only considering tagged jets, right?

I think an Issue could be, if you do not consider all jets, is that the mistagging isn't taking into account properly for the SFs.

Since Jan is an expert on this I would orient myself on his ttbb config (https://github.com/kit-cn-cms/karim/blob/dev_nanoAOD/configs/calculate_ttbb_itFit.py) :D

**Comment by nshadskiy** [comment]
The thing is that we use different jet pT cuts for not-btagged Jets and btagged Jets. If I understood Martin correctly, "taggable" (not tagged yet) jets are all jets with pT higher than 20 GeV. So this should be fine.
And as Martin shows for some (not all) ttbar events the calculated weights look reasonable around 1. 

Therefore I thought that the problem might be during the application of the weights (in Hogwarts).

**Comment by MartMarz** [comment]
Those are not tagged Jets but taggable Jets. The name is quiet confusing I admit. The Problem is that for the reason of additional satistics we allow tagged jets to be of lower pT. 20 instead of 30 GeV. Therefore I loop over alle "taggable" Jets which have the same conditions as the cleanJets but with lower pT. This means that all taggable Jets of 30GeV or more are included in the cleanJet array. The condition is chosen so also tagged Jets below 30GeV are included in the Weight calculation.

I did beforehand "only" use the clean Jets but still the same effect occured.

My config is based on the ttbb config made by Jan. I just renamed the variables for the bsm Analysis and now added the low energy bJets in the calculation.

**Comment by MartMarz** [comment]
To check my weights I compared them with Jans ttbb UL analysis. Just the overall ditribution.
[jan_ttbbUL_TT2_tree2.pdf](https://github.com/kit-cn-cms/karim/files/7970342/jan_ttbbUL_TT2_tree2.pdf)
[martin_bsm_TT2_tree2.pdf](https://github.com/kit-cn-cms/karim/files/7970343/martin_bsm_TT2_tree2.pdf)
Except the huge difference of Entries and number of trees they seem relatively identical. My distribution looks course worse because of the small statistics, but can this really explain my Issue when plotting them in hogwards?

**Comment by MartMarz** [comment]
It also seems quiet strange to me that the friend has fewer entries then the original tree. Did I get this conceptionally wrong or shouldn't the number os SF entries match the number of Events? In my TTTo2nu2l tree_2.root I got 706124 Events while in the bTag Weights I only got round about 4500.
