### ISSUE TITLE
DNN Evaluation Error

### ISSUE THREAD

**Issue by MartMarz** [kit-cn-cms/karim#21]
Hello. I'm currently working on the DNN Evaluation with karim. I already wrote my config and model file but during the evaluation an error occurs. I use the command `python scripts/generateSubmitScripts.py -n 25000 --mode Evaluation -c configs/evaluate_bsm_dnn.py -o /nfs/dust/cms/user/mmarz/NMSSM_friends/UL/friends/2018/27_7/DNN -s scripts_27_7_dnn -m models/bsm_analysis.yml /nfs/dust/cms/user/mmarz/tuple/snape/complete/FatJetClean/2018/Signal_nanoaodv9_UL_MH600_MhS60_hSToBB_hToTauTau
` to generate my submit scripts. I already fixed a 'bug' with the not supported `dataEra` in the `Evaluation` mode. But now I get an error which I do not understand. I pushed my files on the `bsm_di_higgs` branch. Thanks in advance.
```
2022-07-27 12:34:13.009536: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/nfs/dust/cms/user/mmarz/karim/scripts/karim.py", line 130, in <module>
    karim.evaluate_model(
  File "/nfs/dust/cms/user/mmarz/karim/karim/evaluate.py", line 42, in evaluate_model
    entry, error = entry_loader.GetEntry(event)
  File "/nfs/dust/cms/user/mmarz/karim/karim/load/entry.py", line 39, in GetEntry
    data[:,idy] = getattr(event, v)
ValueError: could not broadcast input array from shape (0) into shape (1)
```

**Comment by JanvanderLinden** [comment]
I never adapted the evaluation workflow to the new ntuple configuration, so im pretty sure this doesnt work. I dont know if somebody else gave it a shot? But I doubt it.

Maybe have a look at what Max did for the evaluation of GNNs here:
https://github.com/kit-cn-cms/karim/blob/dev_me_GNN_eval/configs/nlp_eval.py

**Comment by MartMarz** [comment]
Is it feasible for me to do this in a timespan of one or two days?

This is a step that needs to be done if I want a fit at the end right?

**Comment by JanvanderLinden** [comment]
I think we can debug this, sure. The main problem why this might not work is probably due to some hard coded assumptions on the root file structure / variable namings etc that have changed between the old miniAOD ntuples and the new nanoAOD ntuples now.

In the specific case here it might be an issue of the variable namings / array-variables.
So printing out which variable makes this fail already would be helpful

**Comment by michaelwassmer** [comment]
We already debugged it. The problem was that some variables didn't exist for some events and then things crashed.

**Comment by JanvanderLinden** [comment]
Ah I see. If everything works now we can then close this issue?
